apiVersion: v1
kind: Pod
metadata:
  name: k8-webappv1-pod
  namespace: webapp
  labels:
    name: employee
spec:
  containers:
    - name: webapp
      image: 558852840836.dkr.ecr.us-east-1.amazonaws.com/ecr_assignment1_repo:webapp-061612
      env:
        - name: DBPWD
          valueFrom:
            secretKeyRef:
              name: mysql-root-password
              key: MYSQL_ROOT_PASSWORD
        - name: DBPORT
          value: "3306"
        - name: DBHOST
          value: "10.244.0.6"
        - name: DBUSER
          value: "root"
      ports:
        - containerPort: 8080
  dnsPolicy: ClusterFirst
  restartPolicy: Always

