apiVersion: v1
kind: Service
metadata:
  name: employees-service
  labels:
    app: employees
    component: frontend
spec:
  selector:
    app: employees
    component: frontend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

