apiVersion: v1
kind: Service
metadata:
  name: k8-webappv2-service
  namespace: webapp
  labels:
    name: employee
spec:
  type: NodePort
  selector:
    name: employee
    version: "2"
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30001

