apiVersion: v1
kind: Service
metadata:
  name: k8-webappv1-service
  namespace: webapp
  labels:
    name: employee
spec:
  type: NodePort
  selector:
    name: employee
    version: "1"
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000

