apiVersion: v1
kind: Service
metadata:
  name: k8webappv1-service
  labels:
    app: employees
    component: frontend
spec:
  selector:
    app: employees
    component: frontend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP

